name: CI
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
      - name: run Lighthouse CI
        id: lhci
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun
